kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-claim
  namespace: jenkins
spec:
  storageClassName: managed-premium #managed-premium-custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

